[package]
name = "bot"
version = "0.1.0"
edition = "2024"

[dependencies]

stock = { workspace = true }

anyhow = { workspace = true }
dotenvy = "0.15.7"
env_logger = "0.11.8"
log = { workspace = true }
poise = "0.6.1"
serenity = "0.12.5"
tokio = { workspace = true }
